[documentation] bugfix: zsh directory not found
nanvix/documentation pull request #8
Opened 2021-03-18 21:13 UTC by lusantisuper

In this PR, I fixed the issue that zsh can't find directory to build hal.

2021-03-19 14:51 UTC, ppenna requested changes
Some small fixes to go

2021-03-19 14:51 UTC, ppenna commented on 6-contrib/1-build.md
> +sudo bash nanvix-setup-prerequisites.sh   # Get essential tools for building
Watch out for trailing white spaces. We don't need to touch this line ;-)

2021-03-19 14:51 UTC, ppenna commented on 6-contrib/1-build.md
> +cd $WORKDIR'/hal/utils'                   # Enter the source tree
Could we escape the whole argument? It reads cleaner

2021-03-19 14:51 UTC, ppenna commented on 6-contrib/1-build.md
> +export PATH=$PATH':'$WORKDIR'/hal/utils/toolchain/qemu/bin'
Could we escape the whole argument? It reads cleaner

2021-03-19 14:51 UTC, ppenna commented on 6-contrib/1-build.md
> +cd $WORKDIR'/hal'
Could we escape the whole argument? It reads cleaner

2021-03-21 18:03 UTC, lusantisuper commented on 6-contrib/1-build.md
> +cd $WORKDIR'/hal/utils'                   # Enter the source tree
ZSH needs explicity separation from ambient variable to strings.

2021-03-21 18:05 UTC, lusantisuper commented on 6-contrib/1-build.md
> +sudo bash nanvix-setup-prerequisites.sh   # Get essential tools for building
This space is only to match the identation of the other line.

2021-03-21 18:05 UTC, lusantisuper commented on 6-contrib/1-build.md
> +export PATH=$PATH':'$WORKDIR'/hal/utils/toolchain/qemu/bin'
ZSH needs explicity separation from ambient variable to strings.

2021-03-21 18:05 UTC, lusantisuper commented on 6-contrib/1-build.md
> +cd $WORKDIR'/hal'
ZSH needs explicity separation from ambient variable to strings.

2021-03-23 10:38 UTC, ppenna approved these changes

2021-03-23 10:44 UTC, ppenna approved these changes

2021-03-26 10:28 UTC, ppenna approved these changes

2021-03-26 10:28 UTC, merged